# title of website
title: daohang

# description of website
description: tnwss's navigation site

# favicon of website
favicon: "https://github.com/tnwss.png?size=40"

# your website url
url: https://tnwss.github.io/daohang/

# github profile url
github: "https://github.com/tnwss"

# footer message
footer: © 2021-2021 @tnwss

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 社区资讯
      sites:
        - name: 雷锋网
          description: 人工智能和智能硬件领域的互联网科技媒体
          url: https://www.leiphone.com/
        - name: 36kr
          description: 创业资讯、科技新闻
          url: http://36kr.com/
        - name: 数英网
          description: 数字媒体及职业招聘网站
          url: https://www.digitaling.com/
        - name: 猎云网
          description: 互联网创业项目推荐和创业创新资讯
          url: http://www.lieyunwang.com/
        - name: 人人都是产品经理
          description: 产品经理、产品爱好者学习交流平台
          url: http://www.woshipm.com/
        - name: 互联网早读课
          description: 互联网行业深度阅读与学习平台
          url: https://www.zaodula.com/
        - name: 产品壹佰
          description: 为产品经理爱好者提供最优质的产品资讯、原创内容和相关视频课程
          url: http://www.chanpin100.com/
        - name: PMCAFF
          description: 中国第一产品经理人气组织，专注于研究互联网产品
          url: http://www.pmcaff.com/
        - name: 爱运营
          description: 网站运营人员学习交流，专注于网站产品运营管理、淘宝运营。
          url: http://www.iyunying.org/
        - name: 鸟哥笔记
          description: 移动互联网第一干货平台
          url: http://www.niaogebiji.com/
        - name: 古田路9号
          description: 国内专业品牌创意平台
          url: http://www.gtn9.com/
        - name: 优阁网
          description: UI设计师学习交流社区
          url: http://www.uigreat.com/
    - name: 发现产品
      sites:
        - name: NEXT
          description: 不错过任何一个新产品
          url: http://next.36kr.com/posts
        - name: 少数派
          description: 高品质数字消费指南
          url: https://sspai.com/
        - name: 利器
          description: 创造者和他们的工具
          url: http://liqi.io/
        - name: Today
          description: 为身边的新产品喝彩
          url: http://today.itjuzi.com/
        - name: 小众软件
          description: 在这里发现更多有趣的应用
          url: https://faxian.appinn.com/
        - name: Pttrns
          description: Check out the finest collection of design patterns, resources, mobile apps and inspiration
          url: https://www.pttrns.com/
        - name: Collect UI
          description: Daily inspiration collected from daily ui archive and beyond.
          url: http://collectui.com/
        - name: UI uigreat
          description: APP界面截图参考
          url: http://ui.uigreat.com/
        - name: Android Niceties
          description: A collection of screenshots encompassing some of the most beautiful looking Android apps.
          url: http://androidniceties.tumblr.com/
    - name: 网页灵感
      sites:
        - name: Awwwards
          description: Awwwards are the Website Awards that recognize and promote the talent and effort of the best developers, designers and web agencies in the world.
          url: https://www.awwwards.com/
        - name: CSS Design Awards
          description: Website Awards & Inspiration - CSS Gallery
          url: https://www.cssdesignawards.com/
        - name: The FWA
          description: FWA - showcasing innovation every day since 2000
          url: https://thefwa.com/
        - name: Ecommercefolio
          description: Only the Best Ecommerce Design Inspiration
          url: http://www.ecommercefolio.com/
        - name: Lapa
          description: The best landing page design inspiration from around the web.
          url: http://www.lapa.ninja/
        - name: Reeoo
          description: web design inspiration and website gallery
          url: http://reeoo.com/
        - name: Designmunk
          description: Best Homepage Design Inspiration
          url: https://designmunk.com/
        - name: Best Websites Gallery
          description: Website Showcase Inspiration | Best Websites Gallery
          url: https://bestwebsite.gallery/
        - name: Pages
          description: Curated directory of the best Pages
          url: http://www.pages.xyz/
        - name: SiteSee
          description: SiteSee is a curated gallery of beautiful, modern websites collections.
          url: https://sitesee.co/
        - name: Site Inspire
          description: A CSS gallery and showcase of the best web design inspiration.
          url: https://www.siteinspire.com/
        - name: WebInspiration
          description: 网页设计欣赏,全球顶级网页设计
          url: http://web.uedna.com/
        - name: navnav
          description: A ton of CSS, jQuery, and JavaScript responsive navigation examples, demos, and tutorials from all over the web.
          url: http://navnav.co/
        - name: Really Good UX
          description: A library of screenshots and examples of really good UX. Brought to you by
          url: https://www.reallygoodux.io/
    - name: 摄影图库
      sites:
        - name: Unsplash
          description: Beautiful, free photos.
          url: https://unsplash.com/
        - name: visualhunt
          description: 100% Free High Quality Photos
          url: https://visualhunt.com/
        - name: librestock
          description: 65,084 high quality do-what-ever-you-want stock photos
          url: https://librestock.com/
        - name: pixabay
          description: 可在任何地方使用的免费图片和视频
          url: https://pixabay.com/
        - name: SplitShire
          description: Free Stock Photos and Videos for commercial use.
          url: https://www.splitshire.com/
        - name: StockSnap
          description: Beautiful free stock photos
          url: https://stocksnap.io/
        - name: albumarium
          description: The best place to find & share beautiful images
          url: http://albumarium.com/
        - name: myphotopack
          description: A free photo pack just for you. Every month.
          url: https://myphotopack.com/
        - name: Notaselfie
          description: Photos that happen along the way. You can use the images anyway you like. Have fun!
          url: http://notaselfie.com/
        - name: papers
          description: Wallpapers Every Hour!Hand collected :)
          url: http://papers.co/
        - name: stokpic
          description: Free Stock Photos For Commercial Use
          url: http://stokpic.com/
        - name: 55mm
          description: Use our FREE photos to tell your story!
          url: https://55mm.co/visuals
        - name: thestocks
          description: Use our FREE photos to tell your story!
          url: http://thestocks.im/
        - name: freenaturestock
          description: Exclusive mindblowing freebies for designers and developers
          url: http://freenaturestock.com/
        - name: negativespace
          description: Beautiful, High-Resolution Free Stock Photos
          url: https://negativespace.co/
        - name: gratisography
          description: Free high-resolution pictures you can use on your personal and commercial projects, free of copyright restrictions.
          url: https://gratisography.com/
        - name: imcreator
          description: A curated collection of free web design resources, all for commercial use.
          url: http://imcreator.com/free
        - name: lifeofpix
          description: Free high resolution photography
          url: http://www.lifeofpix.com/
        - name: skitterphoto
          description: Free Stock Photos for Creative Professionals
          url: https://skitterphoto.com/
        - name: mmtstock
          description: Free photos for commercial use
          url: https://mmtstock.com/
        - name: magdeleine
          description: HAND-PICKED FREE PHOTOS FOR YOUR INSPIRATION
          url: https://magdeleine.co/browse/
        - name: jeshoots
          description: New Free Photos & Mockups in to your Inbox!
          url: http://jeshoots.com/
        - name: hdwallpapers
          description: High Definition Wallpapers & Desktop Backgrounds
          url: https://www.hdwallpapers.net
        - name: publicdomainarchive
          description: New 100% Free Stock Photos. Every. Single. Week.
          url: http://publicdomainarchive.com/
    - name: PPT资源
      sites:
        - name: OfficePLUS
          description: OfficePLUS，微软Office官方在线模板网站！
          url: http://www.officeplus.cn/Template/Home.shtml
        - name: 优品PPT
          description: 高质量的模版，而且还有PPT图表，PPT背景图等资源
          url: http://www.ypppt.com/
        - name: PPT+
          description: PPT加直播、录制和分享—PPT+语音内容分享平台
          url: http://www.pptplus.cn/
        - name: PPTMind
          description: 分享高端ppt模板与keynote模板的数字作品交易平台
          url: http://www.pptmind.com/
        - name: tretars
          description: The best free Mockups from the Web
          url: http://www.tretars.com/ppt-templates
        - name: 5百丁
          description: 中国领先的PPT模板共享平台
          url: http://ppt.500d.me/
    - name: 图形创意
      sites:
        - name: photoshop
          description: Photoshop不需要解释
          url: https://www.adobe.com/cn/products/photoshop.html
        - name: Affinity Designer
          description: 专业创意软件
          url: https://affinity.serif.com/
        - name: Illustrator
          description: 矢量图形和插图。
          url: https://www.adobe.com/cn/products/illustrator/
        - name: indesign
          description: 页面设计、布局和出版。
          url: http://www.adobe.com/cn/products/indesign.html
        - name: cinema-4d
          description: Cinema 4D is the perfect package for all 3D artists who want to achieve breathtaking results fast and hassle-free.
          url: https://www.maxon.net/en/products/cinema-4d/overview/
        - name: 3ds-max
          description: 3D modeling, animation, and rendering software
          url: https://www.autodesk.com/products/3ds-max/overview
        - name: Blender
          description: Blender is the free and open source 3D creation suite.
          url: https://www.blender.org/
    - name: 界面设计
      sites:
        - name: Adobe XD
          description: Introducing Adobe XD. Design. Prototype. Experience.
          url: http://www.adobe.com/products/xd.html
        - name: invisionapp
          description: Powerful design prototyping tools
          url: https://www.invisionapp.com/
        - name: marvelapp
          description: Simple design, prototyping and collaboration
          url: https://marvelapp.com/
        - name: Muse CC
          description: 无需利用编码即可进行网站设计。
          url: https://creative.adobe.com/zh-cn/products/download/muse
        - name: figma
          description: Design, prototype, and gather feedback all in one place with Figma.
          url: https://www.figma.com/
    - name: 交互动效
      sites:
        - name: Adobe After Effects CC
          description: 电影般的视觉效果和动态图形。
          url: https://www.adobe.com/cn/products/aftereffects/
        - name: principle
          description: Animate Your Ideas, Design Better Apps
          url: http://principleformac.com/
        - name: flinto
          description: Flinto is a Mac app used by top designers around the world to create interactive and animated prototypes of their app designs.
          url: https://www.flinto.com/
        - name: framer
          description: Design everything from detailed icons to high-fidelity interactions—all in one place.
          url: https://framer.com/
        - name: ProtoPie
          description: 高保真交互原型设计
          url: http://www.protopie.cn/
    - name: 在线配色
      sites:
        - name: khroma
          description: Khroma is the fastest way to discover, search, and save color combos you'll want to use.
          url: http://khroma.co/generator/
        - name: uigradients
          description: Beautiful colored gradients
          url: https://uigradients.com
        - name: gradients
          description: Curated gradients for designers and developers
          url: http://gradients.io/
        - name: Coolest
          description: Coolest handpicked Gradient Hues for your next super ⚡ amazing stuff
          url: https://webkul.github.io/coolhue/
        - name: webgradients
          description: WebGradients is a free collection of 180 linear gradients that you can use as content backdrops in any part of your website.
          url: https://webgradients.com/
        - name: grabient
          description: 2017 Grabient by unfold
          url: https://www.grabient.com/
        - name: thedayscolor
          description: The daily color digest
          url: http://www.thedayscolor.com/
        - name: flatuicolors
          description: Copy Paste Color Pallette from Flat UI Theme
          url: http://flatuicolors.com/
        - name: coolors
          description: The super fast color schemes generator!
          url: https://coolors.co/
        - name: colorhunt
          description: Beautiful Color Palettes
          url: http://www.colorhunt.co/
        - name: Adobe Color CC
          description: Create color schemes with the color wheel or browse thousands of color combinations from the Color community.
          url: https://color.adobe.com/zh/create/color-wheel
        - name: flatuicolorpicker
          description: Best Flat Colors For UI Design
          url: http://www.flatuicolorpicker.com/
        - name: trianglify
          description: Trianglify Generator
          url: http://qrohlf.com/trianglify-generator/
        - name: klart
          description: Beautiful colors and designs to your inbox every week
          url: https://klart.co/colors/
        - name: vanschneider
          description: Color Claim was created in 2012 by Tobias van Schneider with the goal to collect & combine unique colors for my future projects.
          url: http://www.vanschneider.com/colors
    - name: 在线工具
      sites:
        - name: tinypng
          description: Optimize your images with a perfect balance in quality and file size.
          url: https://tinypng.com/
        - name: goqr
          description: create QR codes for free (Logo, T-Shirt, vCard, EPS)
          url: http://goqr.me/
        - name: ezgif
          description: simple online GIF maker and toolset for basic animated GIF editing.
          url: https://ezgif.com
        - name: Android 9 patch
          description: Android 9-patch shadow generator fully customizable shadows
          url: http://inloop.github.io/shadow4android/
        - name: screen sizes
          description: Viewport Sizes and Pixel Densities for Popular Devices
          url: http://screensiz.es/
        - name: svgomg
          description: SVG在线压缩平台
          url: https://jakearchibald.github.io/svgomg/
        - name: 稿定抠图
          description: 免费在线抠图软件,图片快速换背景-抠白底图
          url: https://www.gaoding.com
    - name: 设计规范
      sites:
        - name: Design Guidelines
          description: Design Guidelines — The way products are built.
          url: http://designguidelines.co/
        - name: Awesome design systems
          description: A collection of awesome design systems
          url: https://github.com/alexpate/awesome-design-systems
        - name: Material Design
          description: Introduction - Material Design
          url: https://material.io/guidelines/
        - name: Human Interface Guidelines
          description: Human Interface Guidelines iOS
          url: https://developer.apple.com/ios/human-interface-guidelines
        - name: Photoshop Etiquette
          description: PS礼仪-WEB设计指南
          url: http://viggoz.com/photoshopetiquette/
 
